redis:
  image: redis
  ports:
    - "6739:6739"
api:
  build: ./api
  volumes:
    - ./api:/usr/src/app
  ports:
    - "3000:3000"
  links:
    - redis
web:
  build: ./web
  volumes:
    - ./web/public:/usr/share/nginx/html
  ports:
    - "8080:80"
  links:
    - api
